# name: Build and deploy to MSBuild SSMS

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup MSBuild.exe
#       uses: microsoft/setup-msbuild@v1.0.3
#     - name: Build solution
#       run: msbuild /t:Build /p:Configuration=Release ./TimeTac.Database/TimeTac.Database.sqlproj
#     - name: Publish to MSBuild SSMS
#       run: sqlpackage.exe /a:Publish /tsn:(localDb)\MSSQLLocalDB /tdn:TimeTac /tu:myuser /tp:mypassword /sf:./TimeTac/bin/Release/TimeTac.dacpac
